using System.Collections.Immutable;

namespace Bud.Make {
  /// <summary>
  ///   A rule contains information on how to generate a particular output file from a given list of input files.
  /// </summary>
  public class Rule {
    /// <summary>
    ///   The files from which to generate the <see cref="Output" />.
    /// </summary>
    public ImmutableArray<string> Inputs { get; }

    /// <summary>
    ///   The algorithm that builds the <see cref="Output" /> file from the given <see cref="Inputs" />.
    /// </summary>
    public FilesBuilder Recipe { get; }

    /// <summary>
    ///   The output file generated by the <see cref="Recipe" /> from the given <see cref="Inputs" />.
    /// </summary>
    public string Output { get; }

    /// <summary>
    ///   Creates a rule.
    /// </summary>
    public Rule(string output, FilesBuilder recipe, ImmutableArray<string> inputs) {
      Recipe = recipe;
      Inputs = inputs;
      Output = output;
    }
  }
}